GET https://127.0.0.1:27124/

### Read file

GET http://127.0.0.1:27123/vault/lorebook/characters/thea/thea-ashworth.md HTTP/1.1
Accept: application/vnd.olrapi.note+json
Authorization: Bearer 315608501d039714d6139d5da6e0ccd0636e195dc900457210de9124c5c63194

### Get Commands
GET http://127.0.0.1:27123/commands/
Authorization: Bearer 315608501d039714d6139d5da6e0ccd0636e195dc900457210de9124c5c63194

### Dataview query

POST http://127.0.0.1:27123/search/
Authorization: Bearer 315608501d039714d6139d5da6e0ccd0636e195dc900457210de9124c5c63194
Content-Type: application/vnd.olrapi.dataview.dql+txt

TABLE 
  title, 
  tags, 
  characters, 
  summary, 
  order, 
  file.ctime as "ctime"
FROM #lorebook AND !#lorebook-never AND !"system/templates"

### Link fetch query
POST http://127.0.0.1:27123/search/
Authorization: Bearer 315608501d039714d6139d5da6e0ccd0636e195dc900457210de9124c5c63194
Content-Type: application/vnd.olrapi.dataview.dql+txt

TABLE
  unique(filter(file.inlinks, (l) => contains(l.tags, "lorebook") AND !contains(l.tags, "lorebook-never"))) as inlinks,
  unique(filter(file.outlinks, (l) => contains(l.tags, "lorebook") AND !contains(l.tags, "lorebook-never"))) as outlinks 
FROM "lorebook/characters/lucia/lucia.md"

### Write file test

PUT https://127.0.0.1:27124/vault/llmn.json
Content-Type: text/plain
Authorization: Bearer 0f2cc23d50e0562396e91d603d7a417abfd70fd7fe87b9062bc83f213f4c2120

{
    "name": "test"
}

### Empy file

GET https://127.0.0.1:27124/vault/lorebook/empty-test.md
Authorization: Bearer 0f2cc23d50e0562396e91d603d7a417abfd70fd7fe87b9062bc83f213f4c2120
Accept: application/vnd.olrapi.note+json

### 

GET https://127.0.0.1:27124/vault/lorebook/overview.md
Authorization: Bearer 0f2cc23d50e0562396e91d603d7a417abfd70fd7fe87b9062bc83f213f4c2120
Accept: application/vnd.olrapi.note+json